services:
    web:
        build: ./event-loop-frontend
        ports:
            - "3000:3000"
        networks:
            - backend

    backend:
        build: ./event-loop-backend
        ports:
            - "8080:8080"
        networks:
            - backend

networks:
    backend:
